#!/usr/bin/env node

var spawn   = require("child_process").spawn;
var binPath = require("electron-prebuilt");
var options = process.argv.slice(2);

var appExec = spawn(binPath, options.unshift(".") && options);

appExec.stdout.pipe(process.stdout);
appExec.stderr.pipe(process.stderr);
appExec.on("exit", process.exit);
process.on("SIGTERM", function(){
    appExec.kill("SIGTERM");
    process.exit(1)
});